image: "python:3.6"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8

pytest:
  stage: Test
  script:
  - pytest

